spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PaymentServiceDB;encrypt=false;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8082

vnpay:
  tmnCode: 6LWTQHBO
  hashSecret: SZE1HBAGJ0V44LTM85NW9FUE4AM9WVGI
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8082/api/payments/vnpay/return
  ipnUrl: http://localhost:8082/api/payments/vnpay/ipn
